apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-stretch
  labels:
    app: example-stretch
spec:
  selector:
    matchLabels:
      app: example-stretch
  template:
    metadata:
      labels:
        app: example-stretch
    spec:
      containers:
      - name: example-stretch
        image: vandelay/app:stretch
        command: ["node", "src/index.js"]
        resources:
          requests:
            cpu: "10m"
